### PR TITLE
update bio's

### PR DESCRIPTION
**Pull request by daithi-coombes**
update the bio's on the homepage to show:
(profile pics are in email)

```
Bios:

Philip works in UCD on the EU funded research project TURAS. Philip’s background is in architecture and urban design. He is from Belfast and studied in Edinburgh and Glasgow. Dublin has been home for the past 17(!) years.

Aoife works in UCD on the EU funded research project TURAS. Aoife’s background is in geography and geo-ICT. She is from Dublin and studied in NUI Maynooth and University College Cork. Aoife has lived her entire life in Cabra except for a brief escape to Adelaide in 2011.
```

### CODE REVIEW

**Comment by aoifecor** [comment]
Maybe project co-ordinators?

**Comment by daithi-coombes** [comment]
@AlexTNolan (on a sidenote) you may be wondering why this pull request has no issue. There exists a program called [hub](https://github.com/github/hub#git-pull-request) that allows you to turn `issues` into `pr`'s. For now the program works but github are claiming to block this ability soon.

so this pr used to be an issue but was changed by the soon to be deprecated hub tool ;)

**Comment by daithi-coombes** [comment]
@aoifecor without knowing much about the education/research industry `co-ordinators` makes sense to me. Is it not `coordinators`, without the hyphen?

**Comment by daithi-coombes** [comment]
@aoifecor I've pushed the changes to the [dev server](http://dev.reusingdublin.ie/#about) for review.

I was thinking of the bios being hidden and revealed when the hand icon in the `Coordinator Bio's` is clicked

**Comment by aoifecor** [comment]
@daithi-coombes 

Thanks for this. Yes please have them hidden and then revealed when you click on them. Any chance you can make the photos a little smaller and have them aligned? I think co-ordinator has a hyphen.

**Comment by daithi-coombes** [comment]
@aoifecor I've pushed those changes to the live site, so clicking the hand in the `about` section will toggle the `bio's`

**Pull request merged**
